#!/usr/bin/env python3
"""Preflight existing tools and hook destinations before installing local hooks."""

from pathlib import Path
import shutil
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
HOOKS = ("pre-commit", "pre-push", "commit-msg")
PROBES = (
    ("git", "--version"),
    ("bash", "--version"),
    ("swift", "--version"),
    ("pre-commit", "--version"),
    ("git-cliff", "--version"),
)


def run(*command: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(command, cwd=ROOT, text=True, capture_output=True, check=False)


def main() -> int:
    if sys.argv[1:] not in ([], ["--check"]):
        print("Usage: scripts/dev-setup.sh [--check]", file=sys.stderr)
        return 2
    try:
        failures = []
        if sys.version_info < (3, 11):
            failures.append("Python 3.11+ is required for TOML validation.")
        else:
            print(f"OK: Python {sys.version.split()[0]} [{sys.executable}]")
        if sys.platform != "darwin":
            failures.append("Development hooks require macOS and its Swift SDK; source checks remain portable.")
        for command in PROBES:
            executable = shutil.which(command[0])
            result = run(*command) if executable else None
            if result is None or result.returncode != 0 or not result.stdout.strip():
                failures.append(f"Tool unavailable or unhealthy: {' '.join(command)}")
            else:
                print(f"OK: {result.stdout.splitlines()[0]} [{executable}]")
        if failures:
            raise RuntimeError("\n".join(failures) + "\nInstall or repair tools manually; this script never installs software.")
        repository = run("git", "rev-parse", "--show-toplevel")
        if repository.returncode or Path(repository.stdout.strip()).resolve() != ROOT:
            raise RuntimeError("Run setup inside this project's Git working tree.")
        hook_path = run("git", "config", "--get", "core.hooksPath")
        if hook_path.returncode != 1:
            raise RuntimeError("core.hooksPath is configured or unreadable; existing hook routing was preserved.")
        config = run("pre-commit", "validate-config", ".pre-commit-config.yaml")
        if config.returncode:
            raise RuntimeError("Invalid pre-commit configuration:\n" + (config.stderr or config.stdout))
        for hook_type in HOOKS:
            location = run("git", "rev-parse", "--git-path", f"hooks/{hook_type}")
            if location.returncode:
                raise RuntimeError(f"Cannot locate {hook_type} hook.")
            path = Path(location.stdout.strip())
            if not path.is_absolute():
                path = ROOT / path
            if path.is_symlink() or (path.exists() and "File generated by pre-commit" not in path.read_text(encoding="utf-8")):
                raise RuntimeError(f"Existing custom hook preserved: {path}; reconcile it manually before setup.")
        if sys.argv[1:] == ["--check"]:
            print("PASS: tools, configuration and hook destinations; no hooks changed.")
            return 0
        command = ["pre-commit", "install"]
        for hook_type in HOOKS:
            command.extend(("--hook-type", hook_type))
        result = run(*command)
        if result.returncode:
            raise RuntimeError(result.stderr or result.stdout)
        print(result.stdout.strip())
        print("PASS: pre-commit, pre-push and commit-msg installed; no software installed.")
        return 0
    except (OSError, UnicodeError, RuntimeError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
